# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='activity_email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='activity_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='hoodies',
            new_name='hood',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hoodies_name',
            new_name='hood_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hoodies_id',
            new_name='hood_id',
        ),
    ]
