# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodies', '0002_auto_20190531_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image_path',
            field=models.ImageField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
