# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodies', '0003_business_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('path', models.ImageField(upload_to='gallery/')),
                ('neigh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoodies.NeighbourHood')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
